CONST_MONGO_URL = ""
CONST_DATABASE = "TaskManagement"
CONST_USER_COLLECTION = "Users"
CONST_TASK_COLLECTION = "Tasks"

TOKEN_SECRET = "python"
SIGN_IN_METHOD = "HS256"

# 30 days
JWT_EXPIRATION = 86400*30